spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SoleRay/spring-cloud-config-repository.git
          username:
          password:

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    #当有多个eureka的时候，需要配置下面这个，格式：http://${eureka.instance.hostname}:${server.port}/eureka
    service-url:
      defaultZone: http://192.168.0.10:7900/eureka/,http://192.168.0.11:7900/eureka/,http://192.168.0.12:7900/eureka/
server:
  port: 7000