spring:
  application:
    name: distributed-lock
  redis:
    database: 0
#    host: 192.168.0.10
#    port: 6000
    password: redis123456
    sentinel:
      master: mymaster
      nodes: 192.168.0.10:26379,192.168.0.11:26379,192.168.0.12:26379
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    #当有多个eureka的时候，需要配置下面这个，格式：http://${eureka.instance.hostname}:${server.port}/eureka
    service-url:
      defaultZone: http://192.168.0.10:7900/eureka/,http://192.168.0.11:7900/eureka/,http://192.168.0.12:7900/eureka/
