spring:
  application:
    name: order-service
#  activemq:
#    broker-url: tcp://192.168.0.13:61616
#    user: admin
#    password: admin
#    pool:
#      enabled: true
#      max-connections: 100
#  datasource:
#    url: jdbc:mysql://192.168.0.10:3306/db1?useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: 123456
#    driverClassName: com.mysql.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource

server:
  port: 9100

eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.12:7900/eureka/,http://192.168.0.11:7900/eureka/,http://192.168.0.10:7900/eureka/


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
      show-details: always
    routes:
      enabled: true
