spring:
  application:
    name: cloud-zuul
server:
  port: 9100


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka/,http://localhost:7901/eureka/,http://localhost:7902/eureka/
#  instance:
#    hostname: localhost
#    instance-id: cloud-zuul
zuul:
  sensitive-headers:
  routes:
    api-service: /zuul-api-service/**

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
      show-details: always
    routes:
      enabled: true
