spring:
  application:
    name: api-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    #当有多个eureka的时候，需要配置下面这个，格式：http://${eureka.instance.hostname}:${server.port}/eureka
    service-url:
      defaultZone: http://localhost:7900/eureka/,http://localhost:7901/eureka/,http://localhost:7902/eureka/

---
spring:
  profiles: 9000
server:
  port: 9000

---
spring:
  profiles: 9001
server:
  port: 9001

---
spring:
  profiles: 9002
server:
  port: 9002